name: frino_icons
description: The Frino Icon pack available as Flutter Icons. Provides 300+ additional icons to use in your apps.
author: Roman Nowicki <peengle@gmail.com>
version: 1.0.1+4
homepage: https://www.rafalfuczynski.com/frino/icons/
repository: https://github.com/clean/frino_icons

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: FrinoIcons
      fonts:
        - asset: lib/fonts/FrinoIcons.ttf
          weight: 400
